<<<<<<< HEAD
name: MediReserva
publish_to: 'none'
description: Sistema de reservas de consultas médicas MediReserva.
=======
name: MEDIRESERVA
description: "Proyecto MEDIRESERVA - base adaptada del proyecto acumulativo (asincronia, API REST, GPS, mapa y Supabase)."
publish_to: "none"
>>>>>>> 4362380f8704cf00ac6ea9c679a355f156b675c8
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
